name: poetic-forms
parent: default

matches:
  - trigger: "pf:ballade"
    replace: |
      The ballade consists of three stanzas of eight lines, followed by a quatrain. The final line of each stanza (capitalized) is a refrain.
      Each line usually consists of 8 or 10 syllables.
      
      a
      b
      a
      b
      b
      c
      b
      C
      
      a
      b
      a
      b
      b
      c
      b
      C
      
      a
      b
      a
      b
      b
      c
      b
      C
      
      b
      c
      b
      C
    
  - trigger: "pf:pantoum"
    replace: |
      The pantoum consists of an arbitrary number of quatrains where lines 2 and 4 in each quatrain are repeated as lines 1 and 3 in the subsequent quatrain.
      In the final quatrain, lines 1 and 3 of the first quatrain are repeated as lines 2 and 4 (though sometimes reversed).
      
      a1
      b1
      a2
      b2
      
      a3 (b1)
      b3
      a4 (b2)
      b4
      
      a5 (b3)
      b5
      a6 (b4)
      b6
      
      ...
      
      aX (bX-2)
      bX (a1)
      aY (bY-2)
      bY (a2)
    
    
  - trigger: "pf:rondeau"
    replace: |
      15 lines across three stanzas, with the first word or phrase from the first line repeated as a refrain.
      Lines a and b are usually 8 or 10 syllables. The refrain is usually 1-3 words.
      
      a (R)
      a
      b
      b
      a
      
      a
      a
      b
      R
      
      a
      a
      b
      b
      a
      R
    
  - trigger: "pf:rondel"
    replace: |
      A 13 line poem in three stanzas, usually with 8 syllables per line.
      The first two lines (capitalized) act as refrains.
      
      A
      B
      b
      a
      
      a
      b
      A
      B
      
      a
      b
      b
      a
      A
    
  - trigger: "pf:roundel"
    replace: |
      An English variant of the French roundeau, consisting of 11 lines in three stanzas. The opening of the first line becomes a refrain (capitalized).
      
      a
      b
      a
      B
      
      b
      a
      b
      
      a
      b
      a
      B
    
  - trigger: "pf:sestina"
    replace: |
      A 39-line poem with six alternating end words, often written in iambic pentameter.
      Rotate six words as the end words in six stanzas and then include two pairs of the words per line in the final stanza.
      
      a
      b
      c
      d
      e
      f
      
      f
      a
      e
      b
      d
      c
      
      c
      f
      d
      a
      b
      e
      
      e
      c
      b
      f
      a
      d
      
      d
      e
      a
      c
      f
      b
      
      b
      d
      f
      e
      c
      a
      
      b/e
      d/c
      f/a

  - trigger: "pf:sonnet"
    replace: |
      A 14-line poem, often written in iambic pentameter, and which usually rhymes.
      
      a
      b
      a
      b
      
      c
      d
      c
      d
      
      e
      f
      e
      f
      
      g
      g

  - trigger: "pf:terza rima"
    replace: |
      Invented by Dante Alighieri, terza rima is composed of tercets, usually in iambic pentameter.
      Lines one and three rhyme in each tercet, while line two rhymes with lines one and three of the next tercet.
      It can end on a tercet, couplet, or single line.
      
      a
      b
      a
      
      b
      c
      b
      
      c
      d
      c
      
      d
      e
      d
      
      ...
      
      single line -- end rhyme with second line of penultimate tercet (aba/b)
      couplet -- end rhyme both lines with seond line of penultimate tercet (aba/bb)
      tercet -- reverse rhyme scheme of penultimate tercet (aba/bab)
    

  - trigger: "pf:villanelle"
    replace: |
      The villanelle consists of five tercets and a quatrain with line lengths of 8-10 syllables. 
      The first and third lines (capitalized) of the first stanza become refrains that repeat throughout the poem.
      
      A1
      b
      A2
      
      a
      b
      A1
      
      a
      b
      A2
      
      a
      b
      A1
      
      a
      b
      A2
      
      a
      b
      A1
      A2
  